### ISSUE TITLE
Doesn't work with Wine on linux

### ISSUE THREAD

**Issue by logslmao** [amazeedaizee/CustomStreamMaker#3]
Launching the program works fine, yes, but as soon as it launches you get the following screen
![Screenshot_20240820_024257](https://github.com/user-attachments/assets/c1ae80fe-d2d0-4641-80b9-393cb88a20d4)
I cant seem to get around this as corefont process hangs

**Comment by amazeedaizee** [comment]
Hi there, sorry you're having a problem with opening the program.

The program hasn't been previously tested on Linux devices via Wine yet, however I'm happy to help more on this issue.

Just to experiment, I was able to make the program run on Ubuntu 22.0.4 using KDE Plasma through Wine, though for some reason, the program does not seem to be able to properly detect if the Custom Stream Loader mod is installed in the game, nor save the game path after setting it when the program first loads (at least for me), which is pretty annoying.

![image](https://github.com/user-attachments/assets/fda95b39-fc6e-4ad3-8813-5be26d943ba4)

Looking at the exception in the screenshot, perhaps you might need to re-install the corefonts needed? I was able to install any fonts needed with the program by using the tf-mscorefonts-installer without any issue.

**Comment by logslmao** [comment]
Corefonts doesnt work, atleast not for me

**Comment by amazeedaizee** [comment]
Just to clarify, the ms core fonts don't work with this program specifically, or does it not work with any program running on Wine? Are you able to download the ms core fonts, or is it the installer specifically that hangs? How are you downloading and installing the core fonts needed? With what command?

**Comment by logslmao** [comment]
The command is "winetricks corefonts", and i made a new wine prefix but now im getting an error for the follow:

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'CustomStreamMaker.StreamEditor:soundPreview' (4) due to: Could not load file or assembly 'NAudio.WinForms, Version=2.1.0.0, Culture=neutral, PublicKeyToken=e279aa5131008a41' or one of its dependencies.

**Comment by logslmao** [comment]
Also, the problem with it hanging was that Q4WINE was running, i disabled it and the installer ran

**Comment by amazeedaizee** [comment]
Do you know if you have the latest version of the .NET Framework installed? The program uses dotnet48 as its main framework

**Comment by logslmao** [comment]
I installed dotnet48 and i keep getting the error in the original post

**Comment by logslmao** [comment]
I reinstalled corefonts and it didnt work

**Comment by amazeedaizee** [comment]
> The command is "winetricks corefonts", and i made a new wine prefix but now im getting an error for the follow:
> 
> Unhandled Exception: System.TypeLoadException: Could not load type of field 'CustomStreamMaker.StreamEditor:soundPreview' (4) due to: Could not load file or assembly 'NAudio.WinForms, Version=2.1.0.0, Culture=neutral, PublicKeyToken=e279aa5131008a41' or one of its dependencies.

Can I see what happens when you try and run the program in the terminal using wine? And post a screenshot of its output?
I don't think corefonts is really an issue anymore, though I'm wondering why the program isn't recognizing the assembly

**Comment by logslmao** [comment]
![image](https://github.com/user-attachments/assets/e19d8968-5ed0-4c54-9464-a59cdff3ecd6)
I fixed the issue, but i dont remember how, i'll scroll up and check

**Comment by logslmao** [comment]
![image](https://github.com/user-attachments/assets/0bc1daa9-9ca8-4221-86d0-f903be28a523)

**Comment by amazeedaizee** [comment]
If the corefonts issue is appearing again, try installing the mscorefonts directly from Microsoft:

`sudo apt install ttf-mscorefonts-installer`

From this link: https://askubuntu.com/questions/30043/how-to-install-the-package-ttf-mscorefonts-installer

**Comment by logslmao** [comment]
I tried that, it didnt work

**Comment by amazeedaizee** [comment]
Just to confirm, this `/usr/share/fonts/truetype/msttcorefonts/` doesn't exist on your system?

**Comment by logslmao** [comment]
It does, but there isnt a sans serif font

**Comment by amazeedaizee** [comment]
The folder isn't empty though, there are fonts stored in there like Arial and the like right? About 61 files in total

**Comment by logslmao** [comment]
Yes, there are files in there

**Comment by amazeedaizee** [comment]
Interesting how the past error seems to come up again, despite having the required fonts installed.

Perhaps you can try installing allfonts using winetricks and see if that fixes the problem?

Also what Wine version and Linux distro you're using might help in solving the issue (to see if this problem is distro-specific)

**Comment by logslmao** [comment]
wine-8.0 (Debian 8.0~repack-4)
Debian 12.6

**Comment by logslmao** [comment]
kernel is 6.1.0-23-amd64, also installing literally every font worked, thanks!
