### ISSUE TITLE
Dosen't work

### ISSUE THREAD

**Issue by ArThirtyFour** [amazeedaizee/CustomStreamMaker#5]
I downloaded the program and transferred it to the path "...\common\NEEDY GIRL OVERDOSE\BepInEx\plugins\"
And when I opened the .exe, an error pops up.
![image](https://github.com/user-attachments/assets/8fd4799b-489f-4c7c-86f9-510815cb9aab)

**Comment by amazeedaizee** [comment]
Hi there, sorry for the late reply! Have you tried moving the program to the assemblies folder and starting it from there?

**Comment by ArThirtyFour** [comment]
I moving , this work.
